apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-044-deployment

spec:
  template:
    metadata:
      name: first-pod-dec
      labels:
        app: app-044
        type: restapi

    spec:
      containers:
        - name: simple-api
          image: omarelkhatib/app_040:1.0 

  replicas: 6 
  selector:
    matchLabels:
      app: app-044
      type: restapi
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8088
      nodePort: 30005
  selector:
    app: app-044
    type: restapi
