apiVersion: v1
kind: Pod
metadata:
        name: test-nodeselector 
spec:
        containers:
                - name: nginx-image
                  image: nginx
        nodeSelector:
                performance: low 
