apiVersion: v1
kind: Pod
metadata:
        name: test-taint
spec:
        containers:
                - name: nginx-image
                  image: nginx
        tolerations:
                - key: "app"
                  operator: "Equal"
                  value: "myapp"
                  effect: "NoExecute"
